# Generated by Django 3.2.8 on 2022-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='photo',
            field=models.ImageField(default='beverage/no_image.png', upload_to='beverage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='photo',
            field=models.ImageField(default='coffee/no_image.png', upload_to='coffee/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='desert',
            name='photo',
            field=models.ImageField(default='desert/no_image.png', upload_to='desert/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='seasonmenu',
            name='photo',
            field=models.ImageField(default='seasonmenu/no_image.png', upload_to='seasonmenu/%Y/%m/%d'),
        ),
    ]
