# Generated by Django 3.2.8 on 2022-02-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220126_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='sub_cate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
