# Generated by Django 3.2.8 on 2022-04-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_coffee_sub_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='sub_cate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='desert',
            name='sub_cate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
